---
- name: Add docker repo dependencies
  command: yum install -y yum-utils device-mapper-persistent-data lvm2

- name: Add docker repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum:
    name: docker-ce
    state: latest

- name: Start and enable docker
  service:
    name: docker
    state: started
    enabled: yes
